name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: check1
      run: ls
    - name: docker try
      run: docker volume create --name my-vol --opt type=none --opt device=/ --opt o=bind
    - name: list volumes
      run: docker volume ls
    - name: inspect volumes
      run: docker volume inspect my-vol
    - name: Build the Docker image
      run: docker build . -t newmandocker
    - name: Run docker container
#      run: docker run --name newman-container --mount type=bind,source=my-vol,target=/newman newmandocker
      run: docker run --name newman-container -v my-vol newmandocker
    - name: list volumes
      run: docker volume ls
    - name: inspect volumes
      run: docker volume inspect mydir
    - name: Archive production artifacts
      uses: actions/upload-artifact@v3
      with:
          name: test report
          path: |
            /var/lib/docker/volumes/*

