name: github actions

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: crete dir 
      run: mkdir reports
    - name: docker create volume
      run: docker volume create  --name myvol --opt type=none --opt device="/home/runner/work/postman-newman/postman-newman/reports" --opt o=bind
    - name: Build the Docker image
      run: docker build . -t newmandocker
    - name: run docker container
      run: docker run -v myvol:/newman newmandocker
      #continue-on-error: true
    - name: artifacts
      if: ${{ failure() || success()}}
      uses: actions/upload-artifact@v3
      with:
        name: test reports
        path: /home/runner/work/postman-newman/postman-newman/reports
#    - name: Notify slack
 #     if: ${{ failure() || success()}}
  #    env:
   #     SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
    #  uses: pullreminders/slack-action@master
     # with:
      #  args: '{\"channel\":\"C04LVHM9351\",\"text\":\"Hello world\"}'
    - name: Send GitHub Action trigger data to Slack workflow
      if: ${{ failure() || success()}}
      id: slack
      uses: slackapi/slack-github-action@v1.23.0
      with:
        # This data can be any valid JSON from a previous step in the GitHub Action
        payload: |
          {
            "text":"GitHub build result: ${{ job.status }}\n
            ${{ github.event.pull_request.html_url || github.event.head_commit.url }} \n
            {workflow} has {status_message},
            "key": "value",
            "foo": "bar"
          }
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
