name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: create dir
      run: mkdir reports
    - name: check1
      run: ls
    - name: pwd
      run: pwd
    - name: docker try
      run: docker volume create --name myvol --opt type=none --opt device="/home/runner/work/postman-newman/postman-newman/reports" --opt o=bind
    - name: list volumes
      run: docker volume ls
    - name: inspect volumes
      run: docker volume inspect myvol
    - name: Build the Docker image
      run: docker build . -t newmandocker
    - name: Run docker container
#      run: docker run --name newman-container --mount type=bind,source=my-vol,target=/newman newmandocker
      run: docker run -v myvol:/newman newmandocker
    - name: list volumes
      run: docker volume ls
    - name: check1
      run: ls -a reports/
    - name: Archive production artifacts
      uses: actions/upload-artifact@v3
      with:
          name: test report
          path: |
            /reports

