name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: check1
      run: ls
    - name: docker try
      run: docker volume create my-vol
    - name: list volumes
      run: docker volume ls
    - name: inspect volumes
      run: docker volume inspect my-vol
    - name: check1
      run: ls
    - name: Build the Docker image
      run: docker build . -t newmandocker
    - name: check3
      run: ls
    - name: Run docker container
      run: docker run --name newman-container --mount source=reportsvolume,target=/newman newmandocker
    - name: check2
      run: ls
    - name: Archive production artifacts
      uses: actions/upload-artifact@v3
      with:
          name: test report
          path: |
            newman/**

